name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version'     
        required: true
        type: string

jobs:
  release:
    runs-on: macOS-12
    steps:
    
      - name: Setup enviornment
        run: |
          rustup target install aarch64-apple-ios
          rustup target install aarch64-apple-ios-sim
          rustup target install x86_64-apple-ios
          rustup target install aarch64-apple-darwin
          rustup target install x86_64-apple-darwin
          cargo install cargo-lipo

      - uses: actions/checkout@v3

      - uses: actions/checkout@v3
        with:
          repository: ${{secrets.RESPOSITORY}}
          token: ${{secrets.PAT}}
          ref: 'apple'
          path: 'leaf'
          
      - name: Build xcframework
        run: |
          cd leaf
          cd tun2socks
          make xcframework
          cd target
          zip -ry Tun2SocksFramework.xcframework.zip Tun2SocksFramework.xcframework
          
      - name: Detect checksum
        run: |
          export TEMP=`shasum -a 256 leaf/tun2socks/target/Tun2SocksKit.xcframework.zip`
          export CHECKSUM=${TEMP:0:64}
          echo "FILE_CHECKSUM=${CHECKSUM}" >> $GITHUB_ENV
          unset CHECKSUM
          unset TEMP
          
      - name: Update package file
        run: |
          echo "// swift-tools-version: 5.7" > Package.swift
          echo "" >> Package.swift
          echo "import PackageDescription" >> Package.swift
          echo "" >> Package.swift
          echo "let package = Package(" >> Package.swift
          echo "  name: \"Tun2SocksKit\"," >> Package.swift
          echo "  products: [" >> Package.swift
          echo "    .library(name: \"Tun2SocksKit\", targets: [\"Tun2SocksKit\"])" >> Package.swift
          echo "  ]," >> Package.swift
          echo "  targets: [" >> Package.swift
          echo "    .binaryTarget(" >> Package.swift
          echo "      name: \"ClashKit\"," >> Package.swift
          echo "      url: \"https://github.com/daemonomead/Tun2SocksKit/releases/download/${{ github.event.inputs.version }}/Tun2SocksKit.xcframework.zip\"," >> Package.swift
          echo "      checksum: \"${{ env.FILE_CHECKSUM }}\"" >> Package.swift
          echo "    )" >> Package.swift
          echo "  ]" >> Package.swift
          echo ")" >> Package.swift
          
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Tun2SocksKit Release ${{ github.event.inputs.version }}!!!
          commit_user_name: Arror
          commit_user_email: hallo.maqiang@icloud.com
          tagging_message: ${{ github.event.inputs.version }}
          file_pattern: 'Package.swift'
          
      - name: Upload Release
        uses: softprops/action-gh-release@v1
        with:
          draft: false
          tag_name: ${{ github.event.inputs.version }}
          files: leaf/tun2socks/target/Tun2SocksKit.xcframework.zip
