name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version'     
        required: true
        type: string

jobs:
  release:
    runs-on: macOS-12
    steps:
      - uses: actions/checkout@v3
      - uses: actions/checkout@v3
        with:
          repository: 'heiher/hev-socks5-tunnel'
          submodules: 'true'
          path: 'temp'
          
      - name: Build xcframework
        run: |
          cd temp
          make clean
          make PP="xcrun --sdk iphoneos --toolchain iphoneos clang" CC="xcrun --sdk iphoneos --toolchain iphoneos clang" CFLAGS="-arch arm64 -mios-version-min=16.0" LFLAGS="-arch arm64 -mios-version-min=16.0 -Wl,-Bsymbolic-functions" static
          libtool -static ./bin/libhev-socks5-tunnel.a ./third-part/hev-task-system/bin/libhev-task-system.a ./third-part/lwip/bin/liblwip.a ./third-part/yaml/bin/libyaml.a -o libtun2socks.a
          cp temp/src/hev-main.h headers/hev-socks5-tunnel.h
          xcodebuild -create-xcframework -library ./libtun2socks.a -headers ./include -output target/Tun2SocksKit.xcframework
          cd target
          zip -r Tun2SocksKit.xcframework.zip Tun2SocksKit.xcframework
          
      - name: Detect checksum
        run: |
          export TEMP=`shasum -a 256 temp/target/Tun2SocksKit.xcframework.zip`
          export CHECKSUM=${TEMP:0:64}
          echo "FILE_CHECKSUM=${CHECKSUM}" >> $GITHUB_ENV
          unset CHECKSUM
          unset TEMP
          
      - name: Update package file
        run: |
          echo "// swift-tools-version: 5.7" > Package.swift
          echo "" >> Package.swift
          echo "import PackageDescription" >> Package.swift
          echo "" >> Package.swift
          echo "let package = Package(" >> Package.swift
          echo "  name: \"Tun2SocksKit\"," >> Package.swift
          echo "  products: [" >> Package.swift
          echo "    .library(name: \"Tun2SocksKit\", targets: [\"Tun2SocksKit\"])" >> Package.swift
          echo "  ]," >> Package.swift
          echo "  targets: [" >> Package.swift
          echo "    .binaryTarget(" >> Package.swift
          echo "      name: \"Tun2SocksKit\"," >> Package.swift
          echo "      url: \"https://github.com/daemonomead/Tun2SocksKit/releases/download/${{ github.event.inputs.version }}/Tun2SocksKit.xcframework.zip\"," >> Package.swift
          echo "      checksum: \"${{ env.FILE_CHECKSUM }}\"" >> Package.swift
          echo "    )" >> Package.swift
          echo "  ]" >> Package.swift
          echo ")" >> Package.swift
          
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Tun2SocksKit Release ${{ github.event.inputs.version }}!!!
          commit_user_name: Arror
          commit_user_email: hallo.maqiang@icloud.com
          commit_author: Arror <hallo.maqiang@icloud.com>
          tagging_message: ${{ github.event.inputs.version }}
          file_pattern: 'Package.swift'
          
      - name: Upload Release
        uses: softprops/action-gh-release@v1
        with:
          draft: false
          tag_name: ${{ github.event.inputs.version }}
          files: temp/target/Tun2SocksKit.xcframework.zip
