name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version'     
        required: true
        type: string

jobs:
  release:
    runs-on: macOS-12
    steps:
      - uses: actions/checkout@v3
      - uses: actions/checkout@v3
        with:
          repository: 'heiher/hev-socks5-tunnel'
          submodules: 'true'
          path: 'temp'
          
      - name: Build xcframework
        run: |
        
          cd temp
          
          make clean
          
          make PP="xcrun --sdk iphoneos --toolchain iphoneos clang" \
               CC="xcrun --sdk iphoneos --toolchain iphoneos clang" \
               CFLAGS="-arch arm64 -mios-version-min=16.0" \
               LFLAGS="-arch arm64 -mios-version-min=16.0 -Wl,-Bsymbolic-functions" static

          libtool -static -o libhev-socks5-tunnel.a \
                  bin/libhev-socks5-tunnel.a \
                  third-part/lwip/bin/liblwip.a \
                  third-part/yaml/bin/libyaml.a \
                  third-part/hev-task-system/bin/libhev-task-system.a
          
          rm -f include/hev-socks5-tunnel.h
          
          cp src/hev-main.h include/hev-socks5-tunnel.h
          
          xcodebuild -create-xcframework \
                     -library ./libhev-socks5-tunnel.a \
                     -headers ./include \
                     -output ./HevSocks5Tunnel.xcframework
          
          echo "module HevSocks5Tunnel {" > HevSocks5Tunnel.xcframework/ios-arm64/Headers/module.modulemap
          echo "    header \"hev-socks5-tunnel.h\"" >> HevSocks5Tunnel.xcframework/ios-arm64/Headers/module.modulemap
          echo "    export *" >> HevSocks5Tunnel.xcframework/ios-arm64/Headers/module.modulemap
          echo "}" >> HevSocks5Tunnel.xcframework/ios-arm64/Headers/module.modulemap

          zip -r HevSocks5Tunnel.xcframework.zip HevSocks5Tunnel.xcframework
          
      - name: Detect checksum
        run: |
          export TEMP=`shasum -a 256 temp/HevSocks5Tunnel.xcframework.zip`
          export CHECKSUM=${TEMP:0:64}
          echo "FILE_CHECKSUM=${CHECKSUM}" >> $GITHUB_ENV
          unset CHECKSUM
          unset TEMP
          
      - name: Update package file
        run: |
          echo "// swift-tools-version: 5.7" > Package.swift
          echo "" >> Package.swift
          echo "import PackageDescription" >> Package.swift
          echo "" >> Package.swift
          echo "let package = Package(" >> Package.swift
          echo "  name: \"Tun2SocksKit\"," >> Package.swift
          echo "  products: [" >> Package.swift
          echo "    .library(name: \"Tun2SocksKit\", targets: [\"Tun2SocksKit\"])," >> Package.swift
          echo "    .library(name: \"HevSocks5Tunnel\", targets: [\"HevSocks5Tunnel\"])" >> Package.swift
          echo "  ]," >> Package.swift
          echo "  targets: [" >> Package.swift
          echo "    .target(name: \"Tun2SocksKit\", dependencies: [\"HevSocks5Tunnel\"])," >> Package.swift
          echo "    .binaryTarget(" >> Package.swift
          echo "      name: \"HevSocks5Tunnel\"," >> Package.swift
          echo "      url: \"https://github.com/daemooon/Tun2SocksKit/releases/download/${{ github.event.inputs.version }}/HevSocks5Tunnel.xcframework.zip\"," >> Package.swift
          echo "      checksum: \"${{ env.FILE_CHECKSUM }}\"" >> Package.swift
          echo "    )" >> Package.swift
          echo "  ]" >> Package.swift
          echo ")" >> Package.swift
          
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Tun2SocksKit Release ${{ github.event.inputs.version }}!!!
          commit_user_name: Arror
          commit_user_email: hallo.maqiang@icloud.com
          commit_author: Arror <hallo.maqiang@icloud.com>
          tagging_message: ${{ github.event.inputs.version }}
          file_pattern: 'Package.swift'
          
      - name: Upload Release
        uses: softprops/action-gh-release@v1
        with:
          draft: false
          tag_name: ${{ github.event.inputs.version }}
          files: temp/HevSocks5Tunnel.xcframework.zip




